### ISSUE TITLE
RPi 4 issues

### ISSUE THREAD

**Issue by Sploitastik** [xeonqq/co-pilot#7]
Hi! 

Love the project! My new gf keeps not seeing traffic lights and was SO EXCITED to find this! Wanted to make it a gift but I'm stuck after playing with it for over 2 weeks. Just can't get it running. 

I'm using a RPi4 4GB on 32bit Raspbian, current release. 
Running in X as I thought perhaps it was needed to use the camera.
I had tried headless via SSH with the same issues.
Using an 8MP picam on the port by the pins. 
I've tried Python 3.9 fully updated including pip and 3.7 without updating pip. 

I'm unclear if the camera needs to be enabled as legacy in boot.cfg or not? I've tried the python setup as well, but co-pilot doesn't see the camera then. Either way I get good quality stills and video preview. 

I don't have the Corel Accelerator, so added --cpu in cmd and the task manager

Also, don't have a button or LED so I disabled the LED function and removed all but the first "full" co-pilot options in task manager and set the index from -1 to 0.

I have solved a number of issues but now I'm stuck with the below errors.

Thank you for this awesome project and any assistance!

**Trying with Python 3.9:**

copilot@raspberrypi:~/co-pilot $ sudo python3 -m src.main  --ssd_model models/ssd_mobilenet_v2_coco_quant_no_nms_edgetpu.tflite  --label models/coco_labels.txt --score_threshold 0.3 --traffic_lig>
/usr/lib/python3/dist-packages/picamera/encoders.py:519: PiCameraAlphaStripping: using alpha-stripping to convert to non-alpha format; you may find the equivalent alpha format faster
  warnings.warn(
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/copilot/co-pilot/src/camera_capturer.py", line 32, in _run
    self._camera.capture(
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1409, in capture
    camera_port, output_port = self._get_ports(use_video_port, splitter_port)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 559, in _get_ports
    self._check_camera_open()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 540, in _check_camera_open
    raise PiCameraClosed("Camera is closed")
picamera.exc.PiCameraClosed: Camera is closed
Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.

^CException ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt:
copilot@raspberrypi:~/co-pilot $ Output file #0 does not contain any stream

**Trying with Python 3.7:**
sudo python3.7 -m src.main  --ssd_model models/ssd_mobilenet_v2_coco_quant_no_nms_edgetpu.tflite  --label models/coco_labels.txt --score_threshold 0.3 --traffic_light_classification_model models/>
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/copilot/co-pilot/src/main.py", line 10, in <module>
    from .led import Led
  File "/home/copilot/co-pilot/src/led.py", line 1, in <module>
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'

**Comment by xeonqq** [comment]
First, I didn't try with RPi4, out of stock globally...
But based on your error message, I recommend to use python3.7, which is also used in my docker.
Try to do ```python3.7 -m pip install -r requirements_pi.txt``` again. 
And don't use "sudo" when you run the command src.main

Note: without the coral accelerator you might have significant delay on detection.
Fun fact: you can replace the audio here https://github.com/xeonqq/co-pilot/tree/master/sounds/en with your custom sound.

Let me know if you have further questions

**Comment by Sploitastik** [comment]
Hi,

I tried Docker, but numpy fails to install via pip as a dependency. I tried modding the script and install it separately, but no luck due to the older pip version. Updating pip first causes other issues and after trying many different version combos I'm stuck again. 

Would you have a look?

Also, for the camera: Is it supposed to be setup as legacy? 

Thank you!!

**Comment by xeonqq** [comment]
As the first issue here, I want to help you solve it.
If you want, you can send me email, or we can chat on google hangout, it is maybe more efficient to solve your problem. My email xeonqq@gmail.con

**Comment by xeonqq** [comment]
dependency problem, not co-pilot issue
